# Numpy Basics: Arrays and Vectors
## What we will learn?
1) ndarray, an efficient multidimensional array providing fast array-oriented arith‐
metic operations and flexible broadcasting capabilities
2) Mathematical functions for fast operations on entire arrays of data without hav‐
ing to write loops
3) Tools for reading/writing array data to disk and working with memory-mapped
files
4) Linear algebra, random number generation, and Fourier transform capabilities
5) A C API for connecting NumPy with libraries written in C, C++, or FORTRAN

## Data Analysis
1) Fast array-based operations for data munging and cleaning, subsetting and filter‐
ing, transformation, and any other kind of computation
2) Common array algorithms like sorting, unique, and set operations
3) Efficient descriptive statistics and aggregating/summarizing data
4) Data alignment and relational data manipulations for merging and joining heter‐
ogeneous datasets
5) Expressing conditional logic as array expressions instead of loops with if-elif-
else branches
5) Group-wise data manipulations (aggregation, transformation, and function
application)

In [1]:
import numpy as np

In [2]:
# comparing python and numpy performance
my_arr = np.arange(1_000_000) # npumpy
my_list = list(range(1_000_000)) #python 

In [3]:
# multiply numpy array by 2
%timeit my_arr2 = my_arr * 2

1.54 ms ± 26.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [5]:
# multiply python array by 2
%timeit my_list2 = [x * 2 for x in my_list]

48.3 ms ± 102 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


**See the difference? Numpy is much faster than python**

## Numpy ndarray: A Multidimensional Array Object
Array enables us to perform math operations on whole blocks of data using similar syntax to the equivalent operations between scalar elements.

In [8]:
data = np.array([[1.5, 0.1, 3], [0, -3, 6.5]])
data

array([[ 1.5,  0.1,  3. ],
       [ 0. , -3. ,  6.5]])

**Then perfrom math operation:**

In [9]:
data * 10

array([[ 15.,   1.,  30.],
       [  0., -30.,  65.]])

In [10]:
data + data 

array([[ 3. ,  0.2,  6. ],
       [ 0. , -6. , 13. ]])

ndarray is a generic multidimensional container to store homogeneous data. This means that all elements must be in the same type. We can use `shape` to display the size of dimension of the array and `dtype` to display the data type of the arrray. 

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

In [15]:
# create an array 
data1 = [6, 7.5, 8, 0, 1] # python list containing int and float data
arr1 = np.array(data1) # use array function from numpy to create new numpy array
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [17]:
# what about ndarray?
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]] # python nested list 
arr2 = np.array(data2) # use array function for numpy to convert python nested list to numpy array
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
# How can we know that arr2 is multidimensional array? Well we can check it by using ndim function 
arr2.ndim

2

In [19]:
# The output above shows that the arr2 has two dimensions. We can also confirm this by using shape function
arr2.shape

(2, 4)

In [20]:
# many ways of creating arrays in numpy
np.zeros(10) # create an array containing 10 zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.ones(20) # create an array containing 20 1s

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [23]:
# higher dimensional?
np.zeros((3, 6)) # 3 dimensions with 6 elements of each dimension

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [27]:
np.ones((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

#### Data types for ndarrays
It is a special object containing the information/ metadata about data. 

In [28]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [29]:
arr1.dtype

dtype('float64')

In [30]:
arr2.dtype

dtype('int32')

In [31]:
# converting data types
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [34]:
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

In [35]:
# check data type
float_arr.dtype

dtype('float64')

In [36]:
# from floating point to integer
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [37]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [39]:
# string array
numeric_string = np.array(["1.25", "-9.6", "42"], dtype=np.string_)
numeric_string

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [40]:
# converting array string representing number to float
numeric_string.astype(float)

array([ 1.25, -9.6 , 42.  ])

#### Arithmetic with NumPy Arrays
Arrays enable us to express batch operations on data without writing any for loops. This is called vectorization.

In [41]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [42]:
# multiplication *
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [43]:
# subs
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
# div
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [45]:
# Exp
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [47]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [48]:
# comparison 
arr2 > arr1

array([[False,  True, False],
       [ True, False,  True]])

#### Basic Indexing and Slicing

In [50]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
# accessing element at index 5
arr[5]

5

In [52]:
# accessing element at index 5-7 
arr[5:8]

array([5, 6, 7])

In [53]:
# assign scalar value
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [54]:
# consider the following example:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [55]:
arr_slice[1] = 12345

In [56]:
# look at the original array:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [59]:
# now look at this:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

NumPy is designed to be able to work with a very large arrays, that is why copying data is not a number one option since it will cause performance and memory problem. If we really need to copy the data, we can use the `copy()` method: `arr_slice[5:8].copy()`

#### Working with Higher Dimensional Array
In two-dimensional array, the elements at each index are no longer scalars but rather one-dimensional arrays:

In [61]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # create 2 dimensional array
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
arr2d[2] # this index belongs to dimension 3 of the array

array([7, 8, 9])

In [64]:
# So how we can access the individual element on each dimension?
arr2d[2][0] # access element at index 0 of array at index 2

7

In [65]:
# or we can access it like so:
arr2d[2, 0]

7

In [67]:
# what about three dimensional arrays? Consider the following:
arr3d  = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [68]:
# arr3d is a 2 x 3 array:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [70]:
# Both scalar values and arrays can be assigned to arr3d[0]:
old_values = arr3d[0].copy()

In [71]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [72]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
# if we want to bring the old value back, then:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [74]:
# now look at this:
arr3d[1, 0]

array([7, 8, 9])

In [75]:
x = arr3d[1] 
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [76]:
x[0]

array([7, 8, 9])

**Indexing with Slices**

In [77]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [79]:
# Slicing one dimensional array
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [80]:
# Slicing 2-dimensional array
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
arr2d[:2] # selectng two arrays of the axis 0, select

array([[1, 2, 3],
       [4, 5, 6]])